# Generated by Django 4.2.9 on 2024-02-11 14:26

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import faculty.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(message='Only alphabets allowed', regex='^[A-Za-z]*$')])),
                ('last_name', models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(message='Only alphabets allowed', regex='^[A-Za-z]*$')])),
                ('dob', models.DateField(validators=[faculty.models.validate_age])),
                ('highest_qualification', models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(message='Invalid Qualification. Must not have special characters', regex='^[a-zA-Z0-9.]*$')])),
                ('years_of_experience', models.FloatField()),
                ('co_ordinator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='student.course')),
            ],
        ),
    ]
