# Generated by Django 4.2.9 on 2024-02-12 02:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guardian',
            name='contact_number',
            field=models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message='Invalid phone number', regex='^[0-9\\s\\+]*$')]),
        ),
        migrations.AlterField(
            model_name='guardian',
            name='name',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(message='Only alphabets allowed', regex='^[A-Za-z\\s]*$')]),
        ),
        migrations.AlterField(
            model_name='guardian',
            name='relationship',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(message='Only alphabets allowed', regex='^[A-Za-z\\s]*$')]),
        ),
        migrations.AlterField(
            model_name='registration',
            name='first_name',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(message='Only alphabets allowed', regex='^[A-Za-z\\s]*$')]),
        ),
        migrations.AlterField(
            model_name='registration',
            name='last_name',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(message='Only alphabets allowed', regex='^[A-Za-z\\s]*$')]),
        ),
        migrations.AlterField(
            model_name='stream',
            name='name',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(message='Only alphabets allowed', regex='^[A-Za-z\\s]*$')]),
        ),
    ]
