# Generated by Django 4.2.9 on 2024-02-12 05:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_remove_registration_guardian_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='selected_course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='selected_course_registrations', to='student.course'),
        ),
    ]
