# Generated by Django 4.2.9 on 2024-03-08 11:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0003_semester_subject'),
        ('student', '0005_registration_edit_link_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentSemester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('internal_exam1_mark', models.FloatField(blank=True, null=True)),
                ('internal_exam2_marks', models.FloatField(blank=True, null=True)),
                ('assignment_mark', models.FloatField(blank=True, null=True)),
                ('seminar_mark', models.FloatField(blank=True, null=True)),
                ('total_mark', models.FloatField(blank=True, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.course')),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='faculty.faculty')),
                ('registration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.registration')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='faculty.semester')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='faculty.subject')),
            ],
            options={
                'unique_together': {('registration', 'semester', 'subject')},
            },
        ),
    ]
